# Site settings
title: Matheus Barone | Desenvolvedor Front End
description: > # this means to ignore newlines until "baseurl:"
  Um site que conta um pouco do meu trabalho como Desenvolvedor Front End.
baseurl: "" # the subpath of your site, e.g. /blog
url: "mathvbarone.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Matheus Barone
user_description: Um site que conta um pouco do meu trabalho como Desenvolvedor Front End.
user_title: Matheus Barone
email: matheusvbarone@gmail.com
twitter_username: matheusvbarone
github_username:  mathvbarone


# Build settings
markdown: kramdown
permalink: /:title
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Tags
    url: /tags


# exclude my node related stuff
exclude: ['package.json', 'assets/src', 'node_modules']
