# Site settings
title: Matheus Barone - Desenvolvedor Front End
email: matheusvbarone@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Um site que conta um pouco do meu trabalho como Desenvolvedor Front End.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://willianjusten.com.br" # the base hostname & protocol for your site
twitter_username: matheusvbarone
github_username:  mathvbarone

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Tags
    url: /tags


# exclude my node related stuff
exclude: ['package.json', 'assets/src', 'node_modules']
