# Site settings
title: Matheus Barone | Desenvolvedor Front-end
email: matheusvbarone@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sou Matheus Barone, de Santos/SP. Fiz esse site para demonstrar um pouco do meu trabalho, além de repassar o que aprendo trabalhando como Desenvolvedor Front-end.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://matheusbarone.com" # the base hostname & protocol for your site
twitter_username: matheusvbarone
github_username:  mathvbarone

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Tags
    url: /tags
  - title: Sobre mim
    url: /sobre


# exclude my node related stuff
exclude: ['package.json', 'assets/src', 'node_modules']
