# Site settings
title: Matheus Barone | Software Engineer
email: matheusvbarone@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Olá, sou Matheus Barone, de Santos/SP. Trabalho como Software Engineer na Avanade.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://matheusbarone.com" # the base hostname & protocol for your site
twitter_username: matheusvbarone
github_username:  mathvbarone

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Tags
    url: /tags
  - title: Sobre mim
    url: /sobre


files_to_cache:
 - '/assets/dist/js/main.min.js'

pages_to_cache:
  - '/sobre/'
  - '/tags/'
  - '/offline/index.html'


# exclude my node related stuff
exclude: ['package.json', 'assets/src', 'node_modules']
